name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install && yarn add global @lhci/cli@0.4.x
      - run: yarn run build
      - run: lhci autorun
